[tool.poetry]
name = "ARCtrl"
version = "1.0.0"
description = "Library for management of Annotated Research Contexts (ARCs) using an in-memory representation and runtimer agnostic contract systems."
authors = ["Heinrich Lukas Weil <weil@rptu.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"