name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x.x
    - name: Restore fable
      run: dotnet tool restore
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
          node-version: 16
    - name: install node modules
      working-directory: ./
      run: npm install --ignore-scripts
    - name: install node modules ISA
      working-directory: ./src/ISA
      run: npm install
    - name: make script executable
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      run: chmod u+x build.sh
    - name: Test (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      working-directory: ./
      run: ./build.sh runtests
    - name: Test (Windows)
      if: matrix.os == 'windows-latest'
      run: .\build.cmd runtests